---
# tasks file for openssh-server

- name: load OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: install openssh-server and openssh-client
  package: name={{ sshd_packages }} state=latest

- name: template sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
    backup: yes
  notify: restart_sshd
